# permissions for end users to edit imagescannings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagescanning-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagescannings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagescannings/status
  verbs:
  - get
