# permissions for end users to view imagescannings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagescanning-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagescannings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagescannings/status
  verbs:
  - get
